import { v4 as uuidv4 } from "uuid";

const data = {
  products: [
    {
      id: uuidv4(),
      title: "Calça Jeans",
      price: 88.99,
      img: 0,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Shorts",
      price: 68.99,
      img: 1,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Camiseta Brasil",
      price: 58.99,
      img: 2,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Calça Alfaiataria",
      price: 98.99,
      img: 3,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Conjunto Rosa",
      price: 127.99,
      img: 4,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Vestido Azul",
      price: 168.99,
      img: 5,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Conjunto Copa",
      price: 97.99,
      img: 6,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Jaqueta Sarja",
      price: 120.99,
      img: 7,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Blusinha Verde",
      price: 68.99,
      img: 8,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Top",
      price: 62.99,
      img: 9,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Polo Azul",
      price: 58.99,
      img: 10,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Camiseta Listras",
      price: 54.99,
      img: 11,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Camiseta Raglan",
      price: 46.99,
      img: 12,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Cropped Manga",
      price: 78.99,
      img: 13,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Cropped Verde",
      price: 53.99,
      img: 14,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Calça Jeans",
      price: 88.99,
      img: 0,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Shorts",
      price: 68.99,
      img: 1,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Camiseta Brasil",
      price: 58.99,
      img: 2,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Calça Alfaiataria",
      price: 98.99,
      img: 3,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Conjunto Rosa",
      price: 127.99,
      img: 4,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Vestido Azul",
      price: 168.99,
      img: 5,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Conjunto Copa",
      price: 97.99,
      img: 6,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Jaqueta Sarja",
      price: 120.99,
      img: 7,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Blusinha Verde",
      price: 68.99,
      img: 8,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Top",
      price: 62.99,
      img: 9,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Polo Azul",
      price: 58.99,
      img: 10,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Camiseta Listras",
      price: 54.99,
      img: 11,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Camiseta Raglan",
      price: 46.99,
      img: 12,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Cropped Manga",
      price: 78.99,
      img: 13,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
    {
      id: uuidv4(),
      title: "Cropped Verde",
      price: 53.99,
      img: 14,
      description: "ldsakljmklfaslkdkjdaskljjkdsa",
      quantityStock: 124,
      quantitySold: 34,
    },
  ],
};

export default data;
